{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/home/jin/Documents/GitHub/epymarl/src",
    "dependencies": [
      "numpy==1.24.4",
      "PyYAML==5.3.1",
      "sacred==0.8.7",
      "torch==2.4.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [
      {
        "commit": "b488f18e518a1699a241469cd716a3d87bfccc73",
        "dirty": true,
        "url": "https://github.com/srcJin/epymarl.git"
      },
      {
        "commit": "b488f18e518a1699a241469cd716a3d87bfccc73",
        "dirty": true,
        "url": "https://github.com/srcJin/epymarl.git"
      },
      {
        "commit": "b488f18e518a1699a241469cd716a3d87bfccc73",
        "dirty": true,
        "url": "https://github.com/srcJin/epymarl.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources/main_80d2780b213e1a0f1f3b49d89e348d55.py"
      ],
      [
        "run.py",
        "_sources/run_023fa99fc1996ca37434859ee00e5f94.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_d3d13baca1adf5f383b487eaf9deba48.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/jin/anaconda3/envs/epymarl/lib/python3.8/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/main.py\", line 45, in my_main\n    run(_run, config, _log)\n",
    "  File \"/home/jin/Documents/GitHub/epymarl/src/run.py\", line 72, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/home/jin/Documents/GitHub/epymarl/src/run.py\", line 207, in run_sequential\n    episode_batch = runner.run(test_mode=False)\n",
    "  File \"/home/jin/Documents/GitHub/epymarl/src/runners/episode_runner.py\", line 166, in run\n    self._log(cur_returns, cur_stats, log_prefix)\n",
    "  File \"/home/jin/Documents/GitHub/epymarl/src/runners/episode_runner.py\", line 178, in _log\n    self.logger.log_stat(prefix + \"return_mean\", np.mean(returns), self.t_env)\n",
    "AttributeError: 'RootLogger' object has no attribute 'log_stat'\n"
  ],
  "heartbeat": "2024-12-07T23:21:46.921576",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz",
    "hostname": "jin-ubuntu",
    "os": [
      "Linux",
      "Linux-5.15.0-125-generic-x86_64-with-glibc2.17"
    ],
    "python_version": "3.8.20"
  },
  "meta": {
    "command": "my_main",
    "config_updates": {},
    "named_configs": [],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-12-07T23:21:46.138629",
  "status": "FAILED",
  "stop_time": "2024-12-07T23:21:46.922224"
}